#!/bin/bash

# make zsh the default shell
chsh -s $(which zsh)

# load dconf settings
dconf load / < ~/.config/dconf/settings.ini

# install firefox theme
cd firefox-gnome-theme
./scripts/auto-install.sh
