#!/bin/bash

# make zsh the default shell
chsh -s $(which zsh)

# load dconf settings
dconf load / < ~/.config/dconf/settings.ini

# install firefox theme
cd ~/.config/yadm/firefox-gnome-theme
./scripts/auto-install.sh

# install vscode extensions
cd ~/.config/Code/
./setup.sh
